-- Plain pgvector schema (portable profile, design D-3).
-- No provider-specific database features: PostgreSQL + pgvector only.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS embedding_profile (
    profile_id          TEXT PRIMARY KEY,
    provider            TEXT NOT NULL CHECK (provider IN ('hashed', 'vertex')),
    model               TEXT NOT NULL CHECK (btrim(model) <> ''),
    dimension           INTEGER NOT NULL CHECK (dimension > 0),
    config_fingerprint  TEXT NOT NULL UNIQUE
        CHECK (config_fingerprint ~ '^[0-9a-f]{64}$'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS space_generation (
    generation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key      TEXT NOT NULL CHECK (btrim(space_key) <> ''),
    profile_id     TEXT NOT NULL REFERENCES embedding_profile(profile_id),
    state          TEXT NOT NULL CHECK (state IN ('building', 'sealed', 'active', 'retired')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    activated_at   TIMESTAMPTZ,
    UNIQUE (space_key, generation_id),
    CHECK (
        (state IN ('building', 'sealed') AND activated_at IS NULL)
        OR (state IN ('active', 'retired') AND activated_at IS NOT NULL)
    )
);

-- CREATE TABLE IF NOT EXISTS does not update constraints on an existing production
-- table. Discover the two state checks by definition rather than by environment-
-- dependent constraint names, then install the final definitions once.
DO $$
DECLARE
    state_values_ok BOOLEAN;
    activation_state_ok BOOLEAN;
    constraint_row RECORD;
BEGIN
    SELECT bool_or(pg_get_constraintdef(oid) LIKE '%sealed%')
      INTO state_values_ok
      FROM pg_constraint
     WHERE conrelid = 'space_generation'::regclass
       AND contype = 'c'
       AND pg_get_constraintdef(oid) LIKE '%state%'
       AND pg_get_constraintdef(oid) NOT LIKE '%activated_at%';

    SELECT bool_or(
               pg_get_constraintdef(oid) LIKE '%sealed%'
               AND pg_get_constraintdef(oid) LIKE '%activated_at%'
           )
      INTO activation_state_ok
      FROM pg_constraint
     WHERE conrelid = 'space_generation'::regclass
       AND contype = 'c'
       AND pg_get_constraintdef(oid) LIKE '%state%'
       AND pg_get_constraintdef(oid) LIKE '%activated_at%';

    IF NOT coalesce(state_values_ok, false) OR NOT coalesce(activation_state_ok, false) THEN
        FOR constraint_row IN
            SELECT conname
              FROM pg_constraint
             WHERE conrelid = 'space_generation'::regclass
               AND contype = 'c'
               AND pg_get_constraintdef(oid) LIKE '%state%'
        LOOP
            EXECUTE format(
                'ALTER TABLE space_generation DROP CONSTRAINT %I',
                constraint_row.conname
            );
        END LOOP;

        ALTER TABLE space_generation
            ADD CONSTRAINT space_generation_state_check
            CHECK (state IN ('building', 'sealed', 'active', 'retired'));
        ALTER TABLE space_generation
            ADD CONSTRAINT space_generation_state_activated_check
            CHECK (
                (state IN ('building', 'sealed') AND activated_at IS NULL)
                OR (state IN ('active', 'retired') AND activated_at IS NOT NULL)
            );
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS space_generation_one_active_idx
    ON space_generation (space_key) WHERE state = 'active';

DO $$
DECLARE
    duplicates TEXT;
BEGIN
    SELECT string_agg(format('%s:[%s]', space_key, generation_ids), ', ' ORDER BY space_key)
      INTO duplicates
      FROM (
          SELECT space_key,
                 string_agg(generation_id::text, ',' ORDER BY generation_id) AS generation_ids
            FROM space_generation
           WHERE state IN ('building', 'sealed')
           GROUP BY space_key
          HAVING count(*) > 1
      ) duplicate_spaces;
    IF duplicates IS NOT NULL THEN
        RAISE EXCEPTION 'duplicate in-flight generations: %', duplicates;
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS space_generation_one_inflight_idx
    ON space_generation (space_key) WHERE state IN ('building', 'sealed');

CREATE TABLE IF NOT EXISTS generation_manifest (
    space_key        TEXT NOT NULL,
    generation_id    BIGINT NOT NULL,
    state            TEXT NOT NULL CHECK (state IN ('in_progress', 'complete')),
    revision         BIGINT NOT NULL DEFAULT 1,
    source_counts    JSONB NOT NULL DEFAULT '{}'::jsonb,
    total_chunks     INTEGER,
    page_count       INTEGER,
    skipped_pages    INTEGER,
    suppressed_pages INTEGER,
    started_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at     TIMESTAMPTZ,
    PRIMARY KEY (space_key, generation_id),
    FOREIGN KEY (space_key, generation_id)
        REFERENCES space_generation (space_key, generation_id),
    CHECK (
        (state = 'in_progress' AND completed_at IS NULL AND total_chunks IS NULL)
        OR (state = 'complete' AND completed_at IS NOT NULL AND total_chunks IS NOT NULL)
    )
);

CREATE TABLE IF NOT EXISTS generation_validation (
    space_key         TEXT NOT NULL,
    generation_id     BIGINT NOT NULL,
    checksum          TEXT NOT NULL CHECK (checksum ~ '^[0-9a-f]{64}$'),
    chunk_count       INTEGER NOT NULL CHECK (chunk_count > 0),
    manifest_revision BIGINT NOT NULL,
    profile_id        TEXT NOT NULL REFERENCES embedding_profile(profile_id),
    query_file_sha256 TEXT NOT NULL CHECK (query_file_sha256 ~ '^[0-9a-f]{64}$'),
    query_count       INTEGER NOT NULL,
    validator_version TEXT NOT NULL,
    validated_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (space_key, generation_id),
    FOREIGN KEY (space_key, generation_id)
        REFERENCES space_generation (space_key, generation_id)
);

CREATE TABLE IF NOT EXISTS chunks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key     TEXT NOT NULL,
    generation_id BIGINT,
    chunk_id      TEXT NOT NULL,             -- "<source_id>#<seq>"
    source_id     TEXT NOT NULL,
    title         TEXT NOT NULL,
    heading       TEXT,
    breadcrumb    TEXT,
    content       TEXT NOT NULL,
    embedding     vector(768) NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Existing installations start with PRIMARY KEY (space_key, chunk_id). Add the
-- generation columns first, then replace that key once. Constraint discovery is
-- column-based rather than name-based because PostgreSQL constraint names can vary.
ALTER TABLE chunks
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE chunks ADD COLUMN IF NOT EXISTS generation_id BIGINT;

DO $$
DECLARE
    current_pk_name TEXT;
    current_pk_is_id BOOLEAN;
BEGIN
    SELECT c.conname,
           ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['id']::name[]
      INTO current_pk_name, current_pk_is_id
      FROM pg_constraint c
     WHERE c.conrelid = 'chunks'::regclass AND c.contype = 'p';

    IF current_pk_name IS NOT NULL AND NOT current_pk_is_id THEN
        EXECUTE format('ALTER TABLE chunks DROP CONSTRAINT %I', current_pk_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
         WHERE c.conrelid = 'chunks'::regclass
           AND c.contype = 'p'
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['id']::name[]
    ) THEN
        ALTER TABLE chunks ADD CONSTRAINT chunks_id_pkey PRIMARY KEY (id);
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS chunks_legacy_uniq
    ON chunks (space_key, chunk_id) WHERE generation_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS chunks_generation_uniq
    ON chunks (space_key, generation_id, chunk_id) WHERE generation_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
         WHERE c.conrelid = 'chunks'::regclass
           AND c.confrelid = 'space_generation'::regclass
           AND c.contype = 'f'
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['space_key', 'generation_id']::name[]
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.confkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.confrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['space_key', 'generation_id']::name[]
    ) THEN
        ALTER TABLE chunks
            ADD CONSTRAINT chunks_space_generation_fkey
            FOREIGN KEY (space_key, generation_id)
            REFERENCES space_generation (space_key, generation_id);
    END IF;
END
$$;

ALTER TABLE chunks ADD COLUMN IF NOT EXISTS content_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', content)) STORED;

CREATE INDEX IF NOT EXISTS chunks_space_source_idx ON chunks (space_key, source_id);
CREATE INDEX IF NOT EXISTS chunks_content_tsv_idx ON chunks USING GIN (content_tsv);
-- Trigram GIN index: language-agnostic substring recall (Korean josa variants,
-- English typos/partial matches) fused alongside the english tsvector path.
CREATE INDEX IF NOT EXISTS chunks_content_trgm_idx ON chunks USING GIN (content gin_trgm_ops);
-- Vector index deferred: MVP corpus is small; add HNSW when corpus grows.
