-- Plain pgvector schema (portable profile, design D-3).
-- No provider-specific database features: PostgreSQL + pgvector only.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS embedding_profile (
    profile_id          TEXT PRIMARY KEY,
    provider            TEXT NOT NULL CHECK (provider IN ('hashed', 'vertex')),
    model               TEXT NOT NULL CHECK (btrim(model) <> ''),
    dimension           INTEGER NOT NULL CHECK (dimension > 0),
    config_fingerprint  TEXT NOT NULL UNIQUE
        CHECK (config_fingerprint ~ '^[0-9a-f]{64}$'),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS space_generation (
    generation_id  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key      TEXT NOT NULL CHECK (btrim(space_key) <> ''),
    profile_id     TEXT NOT NULL REFERENCES embedding_profile(profile_id),
    state          TEXT NOT NULL CHECK (state IN ('building', 'active', 'retired')),
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    activated_at   TIMESTAMPTZ,
    UNIQUE (space_key, generation_id),
    CHECK (
        (state = 'building' AND activated_at IS NULL)
        OR (state IN ('active', 'retired') AND activated_at IS NOT NULL)
    )
);

CREATE UNIQUE INDEX IF NOT EXISTS space_generation_one_active_idx
    ON space_generation (space_key) WHERE state = 'active';

CREATE TABLE IF NOT EXISTS chunks (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    space_key     TEXT NOT NULL,
    generation_id BIGINT,
    chunk_id      TEXT NOT NULL,             -- "<source_id>#<seq>"
    source_id     TEXT NOT NULL,
    title         TEXT NOT NULL,
    heading       TEXT,
    breadcrumb    TEXT,
    content       TEXT NOT NULL,
    embedding     vector(768) NOT NULL,
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Existing installations start with PRIMARY KEY (space_key, chunk_id). Add the
-- generation columns first, then replace that key once. Constraint discovery is
-- column-based rather than name-based because PostgreSQL constraint names can vary.
ALTER TABLE chunks
    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE chunks ADD COLUMN IF NOT EXISTS generation_id BIGINT;

DO $$
DECLARE
    current_pk_name TEXT;
    current_pk_is_id BOOLEAN;
BEGIN
    SELECT c.conname,
           ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['id']::name[]
      INTO current_pk_name, current_pk_is_id
      FROM pg_constraint c
     WHERE c.conrelid = 'chunks'::regclass AND c.contype = 'p';

    IF current_pk_name IS NOT NULL AND NOT current_pk_is_id THEN
        EXECUTE format('ALTER TABLE chunks DROP CONSTRAINT %I', current_pk_name);
    END IF;

    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
         WHERE c.conrelid = 'chunks'::regclass
           AND c.contype = 'p'
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['id']::name[]
    ) THEN
        ALTER TABLE chunks ADD CONSTRAINT chunks_id_pkey PRIMARY KEY (id);
    END IF;
END
$$;

CREATE UNIQUE INDEX IF NOT EXISTS chunks_legacy_uniq
    ON chunks (space_key, chunk_id) WHERE generation_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS chunks_generation_uniq
    ON chunks (space_key, generation_id, chunk_id) WHERE generation_id IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
          FROM pg_constraint c
         WHERE c.conrelid = 'chunks'::regclass
           AND c.confrelid = 'space_generation'::regclass
           AND c.contype = 'f'
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.conkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.conrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['space_key', 'generation_id']::name[]
           AND ARRAY(
               SELECT a.attname
               FROM unnest(c.confkey) WITH ORDINALITY AS key(attnum, ord)
               JOIN pg_attribute a
                 ON a.attrelid = c.confrelid AND a.attnum = key.attnum
               ORDER BY key.ord
           ) = ARRAY['space_key', 'generation_id']::name[]
    ) THEN
        ALTER TABLE chunks
            ADD CONSTRAINT chunks_space_generation_fkey
            FOREIGN KEY (space_key, generation_id)
            REFERENCES space_generation (space_key, generation_id);
    END IF;
END
$$;

ALTER TABLE chunks ADD COLUMN IF NOT EXISTS content_tsv tsvector
    GENERATED ALWAYS AS (to_tsvector('english', content)) STORED;

CREATE INDEX IF NOT EXISTS chunks_space_source_idx ON chunks (space_key, source_id);
CREATE INDEX IF NOT EXISTS chunks_content_tsv_idx ON chunks USING GIN (content_tsv);
-- Trigram GIN index: language-agnostic substring recall (Korean josa variants,
-- English typos/partial matches) fused alongside the english tsvector path.
CREATE INDEX IF NOT EXISTS chunks_content_trgm_idx ON chunks USING GIN (content gin_trgm_ops);
-- Vector index deferred: MVP corpus is small; add HNSW when corpus grows.
